
import React, { createContext, useContext, useState } from "react";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";





const Context = createContext();

export default function Context_holder(props) {

const [UserCountry,setUserCountry]=useState("")

const [CountrySelectPopUp,setCountrySelectPopUp]=useState(false)

const [Products,setProducts]=useState([// {name:"(by Nutrabay) Instant Whey Protein| Naturally Flavoured & Sweetened with Monk Fruit | No Preservatives, 25g Protein - Dark Chocolate, 1 kg",image:"(by Nutrabay) Instant Whey.jpg",link:"https://amzn.to/3SbawF7", brand:"Athlab",category:"Whey Protein",bestseller:true
  // }, 
  // {name:"(by Nutrabay) CreaPower Micronized Creatine Monohydrate Powder - 100g | 100% Creapure® from Germany | NABL Lab Tested | 3g Creatine/Serving | Increases Muscle Mass, Strength, & Power",image:"(by Nutrabay) CreaPower Micronized Creatine Monohydrate.jpg",link:"https://amzn.to/4jx2L8s", brand:"Athlab",category:"Creatine",bestseller:true
  // },

  
{
  name: "MuscleBlaze Biozyme Performance Whey Protein Powder, Chocolate Hazelnut (2kg / 4.4lbs) | 25g Protein Per Scoop | Clinically Tested 50% Higher Protein Absorption",
  image: "MuscleBlaze Biozyme Performance Whey Protein Powder.jpg",
  brand: "MuscleBlaze",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/3Z0I1xH",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "MuscleBlaze Biozyme Performance Whey Protein Powder, Chocolate Hazelnut (1kg / 2.2lbs) | 25g Protein Per Scoop | Clinically Tested 50% Higher Protein Absorption",
  image: "MuscleBlaze Biozyme Performance Whey Protein Powder.jpg",
  brand: "MuscleBlaze",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/3EBOE2L",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "MuscleBlaze Biozyme Iso-Zero, Low Carb Whey Protein Isolate Powder, 27g Isolate Whey Per Scoop (Ice Cream Chocolate, 1kg / 2.2lbs) | USA Patent-Published Enhanced Absorption Formula (EAF)",
  image: "MuscleBlaze Biozyme Iso-Zero, Low Carb Whey Protein Isolate Powder.jpg",
  brand: "MuscleBlaze",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/3Ys1A1U",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "MuscleBlaze 100% Clean Raw Whey Protein Isolate (Unflavoured, 1kg) | 27g Protein per Scoop | Easy to Digest",
  image: "MuscleBlaze  Clean Raw Whey Protein Isolate (Unflavoured, 1kg).jpg",
  brand: "MuscleBlaze",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/4lZWILo",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "MuscleBlaze Micronised Creatine Monohydrate CreAMP Powder, Unflavoured (32 Servings, 100g) | Trustified Certified Creatine",
  image: "MuscleBlaze Micronised Creatine Monohydrate CreAMP Powder, Unflavoured.jpg",
  brand: "MuscleBlaze",
  category: "Creatine",
  bestseller: true,
  IN: "https://amzn.to/42HQzvU",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "MuscleBlaze Micronised Creatine Monohydrate CreAMP Powder, Citrus Blast (25 Servings, 100g) | Trustified Certified Creatine",
  image: "MuscleBlaze Micronised Creatine Monohydrate CreAMP Powder, Citrus Blast.jpg",
  brand: "MuscleBlaze",
  category: "Creatine",
  bestseller: true,
  IN: "https://amzn.to/4iMnPa4",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "MuscleBlaze Raw Whey Protein Concentrate (Unflavoured, 1kg) | Light & Clean Protein | Easy to Digest",
  image: "MuscleBlaze Raw Whey Protein Concentrate (Unflavoured, 1kg).jpg",
  brand: "MuscleBlaze",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/4jZ3EX8",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "MuscleBlaze 100% Clean Raw Whey Protein Concentrate (Unflavoured, 1kg) | Easy to Digest",
  image: "MuscleBlaze Clean Raw Whey Protein Concentrate (Unflavoured, 1kg).jpg",
  brand: "MuscleBlaze",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/3GCosp3",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "MuscleBlaze Omega 3 Fish Oil (90 Capsules) | Trustified Certified for Accuracy & Purity | 1000mg Omega 3 with 180mg EPA & 120mg DHA",
  image: "MuscleBlaze Omega 3 Fish Oil (90 Capsules).jpg",
  brand: "MuscleBlaze",
  category: "Fish Oil",
  bestseller: true,
  IN: "https://amzn.to/4lZfRgl",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "MuscleBlaze Biozyme Daily Multivitamin|5-In-1 Supplement With Vitamins,Minerals,Joint,T-Booster Blend|With Us Patent Published Eafa|For Higher Energy & Improved Performance,1 Count,90 Capsules",
  image: "MuscleBlaze Biozyme Daily Multivitamin.jpg",
  brand: "MuscleBlaze",
  category: "Multivitamins",
  bestseller: true,
  IN: "https://amzn.to/43cvQQR",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "MuscleBlaze MB-Vite Daily Multivitamin (60 Tablets) | With 51 Ingredients & 6 Blends, Vitamins & Minerals, Prebiotic & Probiotics, Amino Acid Blends | For Energy, Stamina & Recovery",
  image: "MuscleBlaze MB-Vite Daily Multivitamin (60 Tablets).jpg",
  brand: "MuscleBlaze",
  category: "Multivitamins",
  bestseller: true,
  IN: "https://amzn.to/3GFhsYQ",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "MuscleBlaze Steel Pro Shaker 700 ml with Steel Whisk, Leakproof Gym Shaker Bottle for Supplements, Midnight Black",
  image: "MuscleBlaze Steel Pro Shaker 700 ml with Steel Whisk.jpg",
  brand: "MuscleBlaze",
  category: "Shaker",
  bestseller: true,
  IN: "https://amzn.to/3Sjd9ol",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

  {name:"Optimum Nutrition Gold Standard 100% Whey Protein Powder for Muscle Growth and Recovery with Glutamine and Natural BCAA Amino Acids 30 Servings, 900 g",image:"Optimum Nutrition Gold Standard Whey Protein Powder.jpg", brand:"Optimum Nutrition",category:"Whey Protein",bestseller:true,
    IN:"",
    US:"https://amzn.to/4cY7pKf",
    GB:"https://amzn.to/3YXRaHh",
    CA:"https://amzn.to/3EGR1Bk",
    FR:"https://amzn.to/3ESFzT1",
    DE:"https://amzn.to/4iFSntV",
    IT:"https://amzn.to/432yAzg",

  },

  {name:"Optimum Nutrition Micronised Creatine Powder, 100% Pure Creatine Monohydrate Powder for Performance and Muscle Power, Unflavoured Shake, 93 Servings, 317 g",image:"Optimum Nutrition (ON) Micronized Creatine Powder.jpg", brand:"Optimum Nutrition",category:"Creatine",bestseller:true,
    IN:"",
    US:"https://amzn.to/3SffQax",
    GB:"https://amzn.to/3YRIRN5",
    CA:"https://amzn.to/4lRbt3b",
    FR:"https://amzn.to/4jQVqR4",
    DE:"https://amzn.to/3Yr1veK",
    IT:"https://amzn.to/3YZNGUL",


  },
  {
    name: "Dymatize Nutrition ISO100 Hydrolyzed Whey Protein Isolate | Fast-Digesting | Muscle Recovery Formula with Amino Acids | Low Sugar & Fat | Cookies & Cream | 5 Lbs",
    image: "Dymatize Nutrition ISO100 Hydrolyzed Whey Protein Isolate.jpg",
    brand: "Dymatize",
    category: "Whey Protein",
    bestseller: true,
    IN: "https://amzn.to/4jY0NOm",
    US: "https://amzn.to/3YXqo1L",
    GB: "https://amzn.to/4lRy2EZ",
    CA: "https://amzn.to/44dewfE",
    FR: "https://amzn.to/3GB4Ce3",
    DE: "https://amzn.to/3GtPTBE",
    IT: "https://amzn.to/3S4u0LP",
  },
  
  {
    name: "Dymatize Nutrition Elite 100% Whey Protein | Muscle Recovery | 25g Protein, 5.5g BCAA | Fast-Absorbing Protein | Gluten-Free | Blend with BCAAs & Glutamine | Rich Chocolate | 5 Lbs",
    image: "Dymatize Nutrition Elite 100 Whey Protein.jpg",
    brand: "Dymatize",
    category: "Whey Protein",
    bestseller: true,
    IN: "https://amzn.to/4kjfmfN",
    US: "https://amzn.to/3Shg9BE",
    GB: "https://amzn.to/4jsPSwe",
    CA: "https://amzn.to/3GC1PkU",
    FR: "https://amzn.to/3YVlmCQ",
    DE: "https://amzn.to/4jXqgay",
    IT: "https://amzn.to/3YpLyWc",
  }

,  
{
  name: "MuscleTech Nitro-Tech Whey Protein, 1.81kg (4lbs), Milk Chocolate, 30g Protein, 3g creatine monohydrate, 6.7g BCAA, ultimate muscle building formula, increase strength & performance",
  image: "MuscleTech Nitro-Tech Whey Protein.jpg",
  brand: "MuscleTech",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/4d93Hxx",
  US: "https://amzn.to/3ShNtIM",
  GB: "https://amzn.to/3YZ9orX",
  CA: "https://amzn.to/4lZ17ye",
  FR: "https://amzn.to/3GzWgmS",
  DE: "https://amzn.to/43dxYYE",
  IT: "https://amzn.to/4d2mwmb",
},

{
  name: "Jacked Factory Creatine Monohydrate Powder 425g - Canadian-Owned Informed Choice Certified Supplement for Increased Muscle Mass*, Improved Strength, Power, & Performance** - 85 Servings, Unflavored",
  image: "Jacked Factory Creatine Monohydrate Powder 425g.jpg",
  brand: "Jacked Factory",
  category: "Creatine",
  bestseller: true,
  IN: "",
  US: "https://amzn.to/4jD97Dy",
  GB: "",
  CA: "https://amzn.to/431VA1e",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "MuscleTech Platinum 100% Creatine Powder (Unflavoured - 250 Gram,83 Serves),Scientifically Researched to Build Muscle - Increase Muscle Power,Boost Strength & Enhance Performance,1 count,83 servings",
  image: "MuscleTech Platinum 100 Creatine Powder.jpg",
  brand: "MuscleTech",
  category: "Creatine",
  bestseller: true,
  IN: "https://amzn.to/4jY5jwd",
  US: "https://amzn.to/3Z1MKz9",
  GB: "https://amzn.to/3RIw8Zt",
  CA: "https://amzn.to/3GALXyY",
  FR: "",
  DE: "https://amzn.to/3GDSCbF",
  IT: "",
},

{
  name: "Optimum Nutrition Micronized Creatine Monohydrate Powder, Unflavored, 240 Servings, 1200 Grams",
  image: "Optimum Nutrition (ON) Micronized Creatine Powder.jpg",
  brand: "Optimum Nutrition",
  category: "Creatine",
  bestseller: true,
  IN: "",
  US: "https://amzn.to/43lbkg3",
  GB: "https://amzn.to/3EBHhZ7",
  CA: "https://amzn.to/4lZ2M6W",
  FR: "https://amzn.to/431WQS0",
  DE: "https://amzn.to/44SS3EN",
  IT: "https://amzn.to/4m36BIk",
},

{
  name: "Optimum Nutrition Gold Standard Pre Workout Energy Powder Drink with Creatine Monohydrate, Beta Alanine, Caffeine & Vitamin B Complex by ON - Fruit Punch, 30 Servings, 330g",
  image: "Optimum Nutrition Gold Standard Pre Workout Energy Powder Drink.jpg",
  brand: "Optimum Nutrition",
  category: "Pre Workout",
  bestseller: true,
  IN: "",
  US: "https://amzn.to/4iU4Ev6",
  GB: "https://amzn.to/3GAMKQs",
  CA: "",
  FR: "https://amzn.to/3YqxHyQ",
  DE: "https://amzn.to/4m2efmk",
  IT: "https://amzn.to/4m2ei1u",
},

{
  name: "Optimum Nutrition Serious Mass, Weight Gainer Protein Powder, Mass Gainer, Vitamin C and Zinc for Immune Support, Creatine, Vanilla, 6 Pound (Packaging May Vary)",
  image: "Optimum Nutrition Serious Mass.jpg",
  brand: "Optimum Nutrition",
  category: "Mass & Weight Gainers",
  bestseller: true,
  IN: "",
  US: "https://amzn.to/3EVkxDi",
  GB: "https://amzn.to/4jY894l",
  CA: "https://amzn.to/4jY8wff",
  FR: "https://amzn.to/44frvNT",
  DE: "https://amzn.to/4k68jXH",
  IT: "https://amzn.to/3RKB0xa",
},

  
{
  name: "RAW Whey Isolate Protein Powder, Birthday Cake (CBUM Itholate Protein) - 100% Grass-Fed Sports Nutrition Powder for Muscle Growth & Recovery - Low-Fat, Low Carb - 25 Servings",
  image: "RAW Whey Isolate Protein Powder, Birthday Cake.jpg",
  brand: "Get Raw Nutrition",
  category: "Whey Protein",
  bestseller: true,
  IN: "",
  US: "https://amzn.to/43lgQPN",
  GB: "https://amzn.to/4iIOGna",
  CA: "https://amzn.to/4iGcPL5",
  FR: "https://amzn.to/4d5zb7U",
  DE: "https://amzn.to/4kl5W3p",
  IT: "",
},

{
  name: "RAW Nutrition Creatine Monohydrate Powder, Unflavored (30 Servings) - Micronized Creatine Monohydrate Supplement for Workout Performance, Build Muscle & Strength - Creatine Powder for Men & Women",
  image: "RAW Nutrition Creatine Monohydrate Powder.jpg",
  brand: "Get Raw Nutrition",
  category: "Creatine",
  bestseller: true,
  IN: "",
  US: "https://amzn.to/3SfXg1V",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "RAW Whey Isolate Protein Powder, Dark Chocolate - 100% Grass-Fed Sports Nutrition Whey Protein Powder for Muscle Growth & Recovery - Low-Fat, Low Carb, Naturally Flavored & Sweetened - 25 Servings",
  image: "RAW Whey Isolate Protein Powder, Dark Chocolate.jpg",
  brand: "Get Raw Nutrition",
  category: "Whey Protein",
  bestseller: true,
  IN: "",
  US: "https://amzn.to/4jZS4LA",
  GB: "https://amzn.to/3YrBnjW",
  CA: "https://amzn.to/4cWWKzs",
  FR: "https://amzn.to/4iGIool",
  DE: "https://amzn.to/4m3QIS2",
  IT: "",
},

{
  name: "RAW Nutrition - Essential Pre - Chris Bumstead Pre Workout Formula, Sports Nutrition Pre-Workout Powders | Men & Womens Drink, Energy Powder for Working Out (Peach Mango)",
  image: "RAW Nutrition - Essential Pre - Chris Bumstead Pre Workout Formula.jpg",
  brand: "Get Raw Nutrition",
  category: "Pre Workout",
  bestseller: true,
  IN: "",
  US: "https://amzn.to/4diDz3z",
  GB: "https://amzn.to/431GrwN",
  CA: "https://amzn.to/4iLp1u6",
  FR: "https://amzn.to/44SZThH",
  DE: "",
  IT: "",
},

{
  name: "BulkSupplements Pure Pea Protein Powder (1 Kilogram)",
  image: "BulkSupplements Pure Pea Protein Powder (1 Kilogram).jpg",
  brand: "BulkSupplements",
  category: "Vegan Plant Protein",
  bestseller: true,
  IN: "https://amzn.to/3YsCpMv",
  US: "https://amzn.to/4jZL1lV",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "BulkSupplements.com Creatine Monohydrate Powder - Creatine Supplement, Micronized Creatine, Creatine Powder - Unflavored & Gluten Free, 5g (5000mg) per Servings, 500g (1.1 lbs) (Pack of 1)",
  image: "BulkSupplements.com Creatine Monohydrate Powder.jpg",
  brand: "BulkSupplements",
  category: "Creatine",
  bestseller: true,
  IN: "",
  US: "https://amzn.to/42Woyzh",
  GB: "",
  CA: "https://amzn.to/4jEZbcG",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "BulkSupplements.com Whey Protein Isolate Powder - Whey Protein Powder, Unsweeteneed, Unflavored & Gluten Free - 30g per Serving, 1kg (2.2 lbs) (Pack of 1)",
  image: "BulkSupplements.com Whey Protein Isolate Powder.jpg",
  brand: "BulkSupplements",
  category: "Whey Protein",
  bestseller: true,
  IN: "",
  US: "https://amzn.to/42Zhylx",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "BPI Sports ISO HD Isolate Protein Vanilla Cookie, 4.8 LBS - 70 Servings",
  image: "BPI Sports ISO HD Isolate Protein Vanilla Cookie.jpg",
  brand: "Bpi Sport",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/43ba7c1",
  US: "https://amzn.to/43a6LGe",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "Bpi Sports Best BCAA Shredded Supplement, Fruit Punch",
  image: "Bpi Sports Best BCAA Shredded Supplement, Fruit Punch.jpg",
  brand: "Bpi Sport",
  category: "BCAAs (Branched Chain Amino Acids)",
  bestseller: false,
  IN: "https://amzn.to/43aCiI1",
  US: "https://amzn.to/4jVzNyR",
  GB: "https://amzn.to/42WtofV",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},



  
{
  name: "Myprotein Creatine Monohydrate Powder, 0.5 Lb (50 Servings) Pure Unflavored Creatine Powder, Post/Pre Workout Supplement for All Sports & Exercises",
  image: "Myprotein Creatine Monohydrate Powder, 0.5 Lb (50 Servings).jpg",
  brand: "MyProtein",
  category: "Creatine",
  bestseller: true,
  IN: "https://amzn.to/4d4i0DB",
  US: "https://amzn.to/4jAswop",
  GB: "https://amzn.to/44n4gl1",
  CA: "https://amzn.to/4d5oylo",
  FR: "https://amzn.to/44hfQhB",
  DE: "https://amzn.to/4k5ZQDR",
  IT: "",
},

{
  name: "Myprotein Impact Whey Protein - Vanilla 1KG",
  image: "Myprotein Impact Whey Protein - Vanilla 1KG.jpg",
  brand: "MyProtein",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/43dFPFy",
  US: "https://amzn.to/4d0VFH3",
  GB: "https://amzn.to/44SBysp",
  CA: "https://amzn.to/3GB9iR3",
  FR: "https://amzn.to/4lWnioy",
  DE: "https://amzn.to/42FY32l",
  IT: "https://amzn.to/4lZDohe",
},

{
  name: "Myprotein Clear Whey Isolate, Peach Tea, 20 Servings",
  image: "Myprotein Clear Whey Isolate, Peach Tea, 20 Servings.jpg",
  brand: "MyProtein",
  category: "Whey Protein",
  bestseller: true,
  IN: "",
  US: "https://amzn.to/44oBzUY",
  GB: "https://amzn.to/44h3KFb",
  CA: "https://amzn.to/3YYIhgA",
  FR: "https://amzn.to/4jAtjWp",
  DE: "https://amzn.to/4j4gUJz",
  IT: "https://amzn.to/3Yu4JOz",
},

{
  name: "Myprotein Impact Whey Protein Isolate, 2.2 Lbs (40 Servings) Vanilla Ice Cream, 22g Protein, 3.5g Glutamine & 4.5g BCAA Per Serving, Protein Shake for Muscle Strength & Recovery",
  image: "Myprotein Impact Whey Protein Isolate, 2.2 Lbs (40 Servings).jpg",
  brand: "MyProtein",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/42ZqFm0",
  US: "https://amzn.to/44nfkPg",
  GB: "https://amzn.to/4jK90WS",
  CA: "https://amzn.to/4iI1Z7p",
  FR: "https://amzn.to/3Z1cJGV",
  DE: "https://amzn.to/4jNrLbN",
  IT: "https://amzn.to/4cWKChQ",
},

 
{
  name: "avvatar Whey Protein | 1Kg | Unflavoured | 27g Protein | 29 Servings | Isolate & Concentrate Blend",
  image: "avvatar Whey Protein  1Kg  Unflavoured.jpg",
  brand: "Avvatar",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/3SnWwI4",
  US: "https://amzn.to/3ESEsCS",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "avvatar Micronized Creatine Monohydrate Powder (100 G,33 Servings)|Unflavoured|Muscle Recovery|Enhance Strength|Boost Recovery,1 Count",
  image: "avvatar Micronized Creatine Monohydrate Powder.jpg",
  brand: "Avvatar",
  category: "Creatine",
  bestseller: true,
  IN: "https://amzn.to/4lXyAsD",
  US: "",
  GB: "",
  CA: "https://amzn.to/42FZ0Yt",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "Isorich Protein | 4.41LB | Malai Kulfi Flavour | 29g Protein | 57 Servings",
  image: "Isorich Protein 4.41LB Malai Kulfi Flavour 29g Protein 57 Servings.jpg",
  brand: "Avvatar",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/44ltC2P",
  US: "https://amzn.to/4iMqhgM",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "The Whole Truth Whey Protein Concentrate Unflavoured |1 kg (2.2 lbs) | 26g Protein per scoop | 6.4g BCAA | 100% Authentic Whey & No Adulteration | Clean and Light | Muscle Building | Vegetarian",
  image: "The Whole Truth Whey Protein Concentrate Unflavoured.jpg",
  brand: "The Whole Truth",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/4k6w16a",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "The Whole Truth Whey Protein Isolate+Concentrate | Cold Coffee 1 kg (2.2 lbs) | 24g Protein/Scoop | 6.6g BCAA | 100% Authentic Whey & No Adulteration | Clean, Light & Easy to Digest | Vegetarian",
  image: "The Whole Truth Whey Protein Isolate Concentrate.jpg",
  brand: "The Whole Truth",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/4lZiHC1",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "AS-IT-IS Nutrition ATOM Whey Protein 1kg | 27g protein | Isolate & Concentrate | Double Rich Chocolate | USA Labdoor Certified | With Digestive Enzymes for better absorption",
  image: "AS-IT-IS Nutrition ATOM Whey Protein 1kg  27g protein.jpg",
  brand: "AS-IT-IS",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/3YVqWFh",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "AS-IT-IS Nutrition Whey Protein Concentrate 80% - 1kg | Unflavoured | tested for purity | Labdoor certified",
  image: "AS-IT-IS Nutrition Whey Protein Concentrate - 1kg.jpg",
  brand: "AS-IT-IS",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/42GoTHB",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "Wellcore - Pure Micronised Creatine Monohydrate | Unflavoured (100g, 33 Servings) | Rapid Absorption | Enhanced Muscle Strength and Power | Fast Recovery | Increased Muscle Mass",
  image: "Wellcore - Pure Micronised Creatine Monohydrate.jpg",
  brand: "Wellcore",
  category: "Creatine",
  bestseller: true,
  IN: "https://amzn.to/4jFOXc0",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "Cutler Nutrition Amplify Pump Pre Workout Caffeine Free Nitric Oxide Booster containing Arginine and Citrulline Pre-Workout for Maximum Pumps",
  image: "Cutler Nutrition Amplify Pump Pre Workout.jpg",
  brand: "Cutler Nutrition",
  category: "Pre Workout",
  bestseller: true,
  IN: "",
  US: "https://amzn.to/3GPMxJ6",
  GB: "",
  CA: "https://amzn.to/4k1gyUz",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "Prevail Pre Workout Powder with Nootropics: Best Pre Workout for Men and Women, Cutting Edge Energy and Focus Supplement with L Citrulline, Alpha GPC, L Tyrosine | Sour Blue Razz, 40 Scoops",
  image: "Prevail Pre Workout Powder with Nootropics.jpg",
  brand: "Cutler Nutrition",
  category: "Pre Workout",
  bestseller: true,
  IN: "",
  US: "https://amzn.to/3GBzJGi",
  GB: "https://amzn.to/3YYbVme",
  CA: "https://amzn.to/3GSnp4o",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "Cutler Nutrition Pure Creatine Monohydrate - 5g Per Serving 50 Servings - Premium Muscle Builder Enhances Strength Performance & Recovery - Unflavored for Easy Mixing",
  image: "Cutler Nutrition Pure Creatine Monohydrate - 5g Per Serving 50 Servings.jpg",
  brand: "Cutler Nutrition",
  category: "Creatine",
  bestseller: true,
  IN: "",
  US: "https://amzn.to/4lUTJE9",
  GB: "https://amzn.to/4m3R4YQ",
  CA: "https://amzn.to/4d0YPKV",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "Cutler Nutrition Total ISO Whey Isolate Protein Powder: Best Tasting Whey Protein Shake, 100% Whey Protein Isolate, Perfect Post Workout Protein Powder Mix, Marshmallow Rice Cereal, 2 Pounds",
  image: "Cutler Nutrition Total ISO Whey Isolate Protein Powder.jpg",
  brand: "Cutler Nutrition",
  category: "Whey Protein",
  bestseller: true,
  IN: "",
  US: "https://amzn.to/3ERpRYo",
  GB: "",
  CA: "https://amzn.to/4iQPAhD",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "Cutler Nutrition Generate EAA and BCAA Powder: Best Branched Chain Amino Acids Supplement with Essential Amino Acids, 5g BCAAs, 2g EAAs for Lean Muscle Mass | Sour Rainbow Candy, 30 Servings",
  image: "Cutler Nutrition Generate EAA and BCAA Powder.jpg",
  brand: "Cutler Nutrition",
  category: "BCAAs (Branched Chain Amino Acids)",
  bestseller: true,
  IN: "",
  US: "https://amzn.to/3EQrC8e",
  GB: "",
  CA: "https://amzn.to/44ZQmp4",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "CON-CRET Concentrated Creatine HCL Powder - supports Muscle, Cognitive, Cellular Energy | No Bloating or Cramps | USA Made & NSF Certified | 60 Micro-dosed servings | Lemon Lime Flavour (57.6gms)",
  image: "CON-CRET Concentrated Creatine HCL Powder.jpg",
  brand: "Con-cret",
  category: "Creatine",
  bestseller: true,
  IN: "https://amzn.to/4k1quh0",
  US: "https://amzn.to/4jAxfq9",
  GB: "",
  CA: "https://amzn.to/3Z0Ot7T",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "Creatine HCl Capsules | Muscle, Cognitive, Cellular Energy Support | No Bloating or Cramps | USA Made & NSF Certified | Creatine Pills (90 ct)",
  image: "Creatine HCl Capsules Muscle, Cognitive, Cellular Energy Support.jpg",
  brand: "Con-cret",
  category: "Creatine",
  bestseller: true,
  IN: "https://amzn.to/4cZjUFD",
  US: "https://amzn.to/4d1qKdG",
  GB: "",
  CA: "https://amzn.to/4lUVwZT",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "Dexter Jackson Signature Series Creatine Powder | Builds Muscle Endurance & Helps To Increase Strength | 100 Servings,300Gm",
  image: "Dexter Jackson Signature Series Creatine Powder.jpg",
  brand: "Dexter Jackson",
  category: "Creatine",
  bestseller: true,
  IN: "https://amzn.to/3ESlKeL",
  US: "https://amzn.to/3Ysk4z8",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "Dexter Jackson Signature Series L-Arginine Promotes Stamina And Performance Free Form Amino Acids Health Supplements 1000 Mg,180 Tablets",
  image: "Dexter Jackson Signature Series L-Arginine.jpg",
  brand: "Dexter Jackson",
  category: "L Arginine",
  bestseller: true,
  IN: "https://amzn.to/42TuvNC",
  US: "https://amzn.to/3Yt05R3",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "Dexter Jackson EAA+BCAA | Improve Exercise Performance & Maximize Muscle Gains | Blue Raspberry Flavor | 390 Gram - Advanced Amino Acid Blend",
  image: "Dexter Jackson EAA+BCAA.jpg",
  brand: "Dexter Jackson",
  category: "BCAAs (Branched Chain Amino Acids)",
  bestseller: true,
  IN: "https://amzn.to/4jP1XMg",
  US: "https://amzn.to/3Yp89lO",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "Black Series Turbo HP Pre Workout | Flavoured, Advanced Formula | Boost Energy and Performance | 45 Servings, 450 Gram (Regular, Blue Raspberry)",
  image: "Black Series Turbo HP Pre Workout.jpg",
  brand: "Dexter Jackson",
  category: "Pre Workout",
  bestseller: true,
  IN: "https://amzn.to/439TaPf",
  US: "https://amzn.to/4lZIKJm",
  GB: "",
  CA: "https://amzn.to/44Uwcgd",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "Dexter Jackson Black Series Isolate Protein Powder | Hydrolyzed Whey Protein Isolate | Gluten-Free | 76 Servings, 5 lbs, 2268g,Chocolate Shake Flavor",
  image: "Dexter Jackson Black Series Isolate Protein Powder.jpg",
  brand: "Dexter Jackson",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/42I2WYP",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "Dexter Jackson Signature Series Whey Gold - Isolate & Hydrolyzed Whey Protein Blend | Double Chocolate Flavor | 67 Servings, 2268G (5 Lbs) - Superior Muscle Fuel For Optimal Performance, powder",
  image: "Dexter Jackson Signature Series Whey Gold.jpg",
  brand: "Dexter Jackson",
  category: "Whey Protein",
  bestseller: true,
  IN: "https://amzn.to/4iI7nHF",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "GAT SPORT Nitraflex (Green Apple) - Powder",
  image: "GAT SPORT Nitraflex (Green Apple)  Powder.jpg",
  brand: "GAT",
  category: "Pre Workout",
  bestseller: true,
  IN: "https://amzn.to/4jCQ24a",
  US: "https://amzn.to/42Tek2J",
  GB: "https://amzn.to/3YvuApr",
  CA: "https://amzn.to/4lXLvuM",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "GAT SPORT Testrol Gold Es, Capsule",
  image: "GAT SPORT Testrol Gold Es, Capsule.jpg",
  brand: "GAT",
  category: "Testosterone Boosters (Natural)",
  bestseller: true,
  IN: "https://amzn.to/4jFTICo",
  US: "https://amzn.to/3YuFn38",
  GB: "",
  CA: "https://amzn.to/4jLIFru",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "GAT SPORT Caffeine - 100 Tablets",
  image: "GAT SPORT Caffeine 100 Tablets.jpg",
  brand: "GAT",
  category: "Vitamins & Supplements",
  bestseller: true,
  IN: "https://amzn.to/4d3HBMP",
  US: "",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "GAT SPORT L-Carnitine Vegetable Capsules - Pack of 60 Capsules",
  image: "GAT SPORT L-Carnitine Vegetable Capsules Pack of 60 Capsules.jpg",
  brand: "GAT",
  category: "L Carnitine",
  bestseller: true,
  IN: "https://amzn.to/434WmdR",
  US: "https://amzn.to/3RJn1HX",
  GB: "",
  CA: "",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "GAT SPORT Men's Multi + Test, Premium Multivitamin Tablets (60 Count)",
  image: "GAT SPORT Men's Multi + Test.jpg",
  brand: "GAT",
  category: "Multivitamins for Men",
  bestseller: true,
  IN: "https://amzn.to/4jAIKhl",
  US: "https://amzn.to/44SgG4w",
  GB: "",
  CA: "https://amzn.to/42FfJv2",
  FR: "",
  DE: "",
  IT: "",
},

{
  name: "GAT SPORT Creatine Monohydrate Powder, 300 Grams, Strength, Brain Health, Anti-oxidant, Endurance, for Men & Women, 2 Month Supply, Unflavored (60 Servings)",
  image: "GAT SPORT Creatine Monohydrate Powder.jpg",
  brand: "GAT",
  category: "Creatine",
  bestseller: true,
  IN: "",
  US: "https://amzn.to/3EBYX6X",
  GB: "",
  CA: "https://amzn.to/4iL7J06",
  FR: "",
  DE: "",
  IT: "",
}

])

  const notify = (msg, status) => {
    toast(msg, {
      position: "top-right",
      type: status === 1 ? "success" : "error",
    });
  };

  const Brands = [
    { name: "Bpi Sport"},
    { name: "MyProtein"},
    
    
    { name: "BulkSupplements"},
     { name: "Get Raw Nutrition"},
    { name: "Jacked Factory"},
    { name: "Nutrabay" },
    { name: "Athlab" },
    { name: "Optimum Nutrition" },
    { name: "MuscleTech" },
    { name: "Dymatize" },
    { name: "Aarkios" },
    { name: "Absolute Nutrition" },
    { name: "Alpino" },
    { name: "AS-IT-IS" },
    { name: "Avvatar" },
    { name: "Aesthetic Nutrition" },
    { name: "Bigmuscles Nutrition" },
    { name: "Bolt" },
    { name: "BPI Sports" },
    { name: "Bigflex" },
    { name: "BestSource Nutrition" },
    { name: "CaliBar" },
    { name: "Carbamide Forte" },
    { name: "Chicnutrix" },
    { name: "Cobra Labs" },
    { name: "Cutler Nutrition" },
    { name: "Condemned" },
    { name: "Con-cret" },
    { name: "Dexter Jackson" },
    { name: "Doctor's Choice" },
    { name: "Dr. Morepen" },
    { name: "Dr. Vaidya's" },
    { name: "Decode Age" },
    { name: "Evlution Nutrition" },
    { name: "FA Core" },
    { name: "Fast&Up" },
    { name: "Foresta Organics" },
    { name: "Gaspari" },
    { name: "GAT" },
    { name: "Genetic Nutrition" },
    { name: "Gibbon Nutrition" },
    { name: "GNC" },
    { name: "Ghost" },
    { name: "Gladful" },
    { name: "HealthAid" },
    { name: "Healthfarm" },
    { name: "HealthyHey Nutrition" },
    { name: "Healthyr-U" },
    { name: "International Protein" },
    { name: "Isopure" },
    { name: "Inja Wellness" },
    { name: "JYM" },
    { name: "Kaged Muscle" },
    { name: "Kapiva" },
    { name: "Kevin Levrone" },
    { name: "Labrada" },
    { name: "Muscle Asylum" },
    { name: "MuscleBlaze" },
    { name: "Mutant" },
    { name: "Myfitness Peanut Butter" },
    { name: "Myfitness" },
    { name: "Mountainor" },
    { name: "Nakpro" },
    { name: "Naturaltein" },
    { name: "Neuherbs" },
    { name: "Now Foods" },
    { name: "Nutrabay" },
    { name: "Nortech Nutrition" },
    { name: "Nourish Organics" },
    { name: "One Science Nutrition" },
    { name: "Pole Nutrition" },
    { name: "Power Gummies" },
    { name: "Proathlix" },
    { name: "Proquest" },
    { name: "ProSupps" },
    { name: "Pure Nutrition" },
    { name: "Perfectil" },
    { name: "Promunch" },
    { name: "Pintola" },
    
    { name: "Redcon1" },
    { name: "RiteBite" },
    { name: "Ronnie Coleman" },
    { name: "Rule1" },
    { name: "RAW Nutrition" },
    { name: "Rasayanam" },
    { name: "SAN" },
    { name: "Scitron" },
    { name: "Swisse" },
    { name: "Steadfast Nutrition" },
    { name: "SuperYou" },
    { name: "Sweetmate" },
    { name: "Setu Nutrition" },
    { name: "TruNativ" },
    { name: "The Whole Truth" },
    { name: "Tata 1mg" },
    { name: "Ultimate Nutrition" },
    { name: "Upakarma Ayurveda" },
    { name: "Unmatched" },
    { name: "Vlado's Himalayan Organics" },
    { name: "Velbiom" },
    { name: "Wellbeing Nutrition" },
    { name: "Wellversed" },
    { name: "Wellwoman" },
    { name: "Wellman" },
    { name: "Wheymill" },
    { name: "YogaBar" },
    { name: "Wellcore" },
    
  ];
  

const Categories = [
  { name: "Shaker" },
  
  { name: "Protein Powders" },
  { name: "Whey Protein" },
  { name: "Protein Blends" },
  { name: "Casein Protein" },
  { name: "Vegan Plant Protein" },
  { name: "High Protein Food" },
  { name: "Protein Bars" },
  { name: "Protein Cookies & Brownies" },
  { name: "Protein Snacks" },
  { name: "Protein Flour" },
  { name: "Mass & Weight Gainers" },
  { name: "Amino Acids" },
  { name: "BCAAs (Branched Chain Amino Acids)" },
  { name: "EAAs (Essential Amino Acids)" },
  { name: "Amino Blends" },
  { name: "Creatine" },
  { name: "L Glutamine" },
  { name: "L Arginine" },
  { name: "Citrulline Malate" },
  { name: "L Leucine" },
  { name: "L Carnitine" },
  { name: "Beta Alanine" },
  { name: "HMB" },
  { name: "Taurine" },
  { name: "L Tyrosine" },
  { name: "Pre Workout" },
  { name: "Electrolytes & Energy Drinks" },
  { name: "Fat Burners" },
  { name: "Testosterone Boosters (Natural)" },
  { name: "Meal Replacements" },
  { name: "Keto Foods" },
  { name: "Diuretic Water Pills" },
  { name: "Vitamins & Supplements" },
  { name: "Multivitamins" },
  { name: "General Multivitamins" },
  { name: "Multivitamins for Men" },
  { name: "Multivitamins for Women" },
  { name: "Multivitamins for Kids" },
  { name: "Single Vitamins" },
  { name: "Vitamin A" },
  { name: "Vitamin B & Complex" },
  { name: "Vitamin C" },
  { name: "Vitamin D" },
  { name: "Vitamin E" },
  { name: "Speciality Supplements" },
  { name: "Supplements for Digestion" },
  { name: "Supplements for Liver & Kidney" },
  { name: "Supplements for Skin & Hair" },
  { name: "Supplements for Diabetes" },
  { name: "Supplements for Immunity" },
  { name: "Supplements for Bone & Joints" },
  { name: "Supplements for Sleep" },
  { name: "Supplements for PCOD" },
  { name: "Supplements for Vitality" },
  { name: "Prenatal Vitamins" },
  { name: "Minerals" },
  { name: "Calcium" },
  { name: "Magnesium" },
  { name: "Zinc" },
  { name: "Iron" },
  { name: "Chromium" },
  { name: "Selenium" },
  { name: "Omega & Essential Fats" },
  { name: "Omega 3 6 9" },
  { name: "Fish Oil" },
  { name: "Flaxseed Oil Capsules" },
  { name: "Antioxidants" },
  { name: "Natural Extracts & Ayurveda" },
  { name: "Health Food & Drinks" },
  { name: "Health Food" },
  { name: "Nut Butters" },
  { name: "Nutrition Bars" },
  { name: "Chyawanprash & Herbal Formulations" },
  { name: "Cereals" },
  { name: "Nuts, Seeds & Grains" },
  { name: "Health Drinks" },
  { name: "Cold Pressed & Cooking Oils" },
  { name: "Sweeteners" },
  { name: "Workout Equipment" },
  { name: "Tshirts" }
];




 




  return (
    <Context.Provider
      value={{
     notify,Products,Categories,Brands,UserCountry,setUserCountry,CountrySelectPopUp,setCountrySelectPopUp,setProducts
      }}
    >
      {props.children}

      <ToastContainer />
    </Context.Provider>
  );
}

export { Context };
